// Mocks generated by Mockito 5.4.6 from annotations
// in hydroflow/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydroflow/features/auth/domain/entities/agency.dart' as _i6;
import 'package:hydroflow/features/auth/domain/entities/salesman.dart' as _i4;
import 'package:hydroflow/features/auth/domain/repositories/agency_repository.dart'
    as _i5;
import 'package:hydroflow/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String?> get onAuthStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChanged),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Stream<_i4.Salesman> getSalesmanStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesmanStream, [uid]),
            returnValue: _i3.Stream<_i4.Salesman>.empty(),
          )
          as _i3.Stream<_i4.Salesman>);

  @override
  _i3.Future<void> signIn({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> checkVersionUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkVersionUpdate, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AgencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgencyRepository extends _i1.Mock implements _i5.AgencyRepository {
  MockAgencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createAgency(_i6.Agency? agency) =>
      (super.noSuchMethod(
            Invocation.method(#createAgency, [agency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.Agency?> getAgencyDetails(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getAgencyDetails, [agencyId]),
            returnValue: _i3.Future<_i6.Agency?>.value(),
          )
          as _i3.Future<_i6.Agency?>);

  @override
  _i3.Future<List<_i4.Salesman>> getSalesmenByAgency(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesmenByAgency, [agencyId]),
            returnValue: _i3.Future<List<_i4.Salesman>>.value(<_i4.Salesman>[]),
          )
          as _i3.Future<List<_i4.Salesman>>);

  @override
  _i3.Future<void> updateWarehouseStock(
    String? agencyId,
    int? quantity,
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWarehouseStock, [
              agencyId,
              quantity,
              type,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetDeviceBinding(String? salesmanId) =>
      (super.noSuchMethod(
            Invocation.method(#resetDeviceBinding, [salesmanId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addSalesman(_i4.Salesman? salesman) =>
      (super.noSuchMethod(
            Invocation.method(#addSalesman, [salesman]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSalesman(_i4.Salesman? salesman) =>
      (super.noSuchMethod(
            Invocation.method(#updateSalesman, [salesman]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isPhoneNumberUnique(
    String? phoneNumber, {
    String? excludeSalesmanId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #isPhoneNumberUnique,
              [phoneNumber],
              {#excludeSalesmanId: excludeSalesmanId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateAgencySettings(
    String? agencyId,
    Map<String, dynamic>? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAgencySettings, [agencyId, settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i6.Agency> getAgencyStream(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getAgencyStream, [agencyId]),
            returnValue: _i3.Stream<_i6.Agency>.empty(),
          )
          as _i3.Stream<_i6.Agency>);
}
