// Mocks generated by Mockito 5.4.6 from annotations
// in watermemo/test/features/stock/presentation/bloc/stock_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:watermemo/features/customers/domain/entities/customer.dart'
    as _i6;
import 'package:watermemo/features/customers/domain/repositories/customer_repository.dart'
    as _i5;
import 'package:watermemo/features/stock/domain/entities/stock_log.dart' as _i4;
import 'package:watermemo/features/stock/domain/repositories/inventory_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i2.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addStock({
    required String? salesmanId,
    required int? quantity,
    String? agencyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addStock, [], {
              #salesmanId: salesmanId,
              #quantity: quantity,
              #agencyId: agencyId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recordDamagedStock({
    required String? salesmanId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordDamagedStock, [], {
              #salesmanId: salesmanId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setOpeningStock({
    required String? salesmanId,
    required int? quantity,
    String? agencyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setOpeningStock, [], {
              #salesmanId: salesmanId,
              #quantity: quantity,
              #agencyId: agencyId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.StockLog?> getTodayStockLogStream(String? salesmanId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayStockLogStream, [salesmanId]),
            returnValue: _i3.Stream<_i4.StockLog?>.empty(),
          )
          as _i3.Stream<_i4.StockLog?>);

  @override
  _i3.Future<void> recordDailyBottleSnapshot({
    required String? salesmanId,
    required int? totalBottles,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordDailyBottleSnapshot, [], {
              #salesmanId: salesmanId,
              #totalBottles: totalBottles,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reconcileStock({
    required String? salesmanId,
    required int? physicalCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reconcileStock, [], {
              #salesmanId: salesmanId,
              #physicalCount: physicalCount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkStockLogsExist(String? salesmanId) =>
      (super.noSuchMethod(
            Invocation.method(#checkStockLogsExist, [salesmanId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<Map<String, int>> getAgencyWarehouseStock(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getAgencyWarehouseStock, [agencyId]),
            returnValue: _i3.Stream<Map<String, int>>.empty(),
          )
          as _i3.Stream<Map<String, int>>);

  @override
  _i3.Future<void> addWarehouseStock({
    required String? agencyId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addWarehouseStock, [], {
              #agencyId: agencyId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.StockLog?> getAgencyStockLogStream(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getAgencyStockLogStream, [agencyId]),
            returnValue: _i3.Stream<_i4.StockLog?>.empty(),
          )
          as _i3.Stream<_i4.StockLog?>);

  @override
  _i3.Future<void> setAgencyOpeningStock({
    required String? agencyId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setAgencyOpeningStock, [], {
              #agencyId: agencyId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAgencyPurchaseStock({
    required String? agencyId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAgencyPurchaseStock, [], {
              #agencyId: agencyId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAgencyRefillStock({
    required String? agencyId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAgencyRefillStock, [], {
              #agencyId: agencyId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recordAgencyDamagedStock({
    required String? agencyId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordAgencyDamagedStock, [], {
              #agencyId: agencyId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> collectEmptyBottles({
    required String? salesmanId,
    required int? quantity,
    required String? agencyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#collectEmptyBottles, [], {
              #salesmanId: salesmanId,
              #quantity: quantity,
              #agencyId: agencyId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkAgencyStockLogsExist(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#checkAgencyStockLogsExist, [agencyId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i5.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Customer>> getCustomers(String? salesmanId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomers, [salesmanId]),
            returnValue: _i3.Stream<List<_i6.Customer>>.empty(),
          )
          as _i3.Stream<List<_i6.Customer>>);

  @override
  _i3.Stream<List<_i6.Customer>> getCustomersByAgency(String? agencyId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersByAgency, [agencyId]),
            returnValue: _i3.Stream<List<_i6.Customer>>.empty(),
          )
          as _i3.Stream<List<_i6.Customer>>);

  @override
  _i3.Future<int> getTotalBottleBalance(String? salesmanId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalBottleBalance, [salesmanId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> addCustomer(_i6.Customer? customer) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomer, [customer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCustomerStatus(
    String? id,
    String? status,
    String? salesmanId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomerStatus, [id, status, salesmanId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCustomer(_i6.Customer? customer) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [customer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> settleAndDeactivate(_i6.Customer? customer) =>
      (super.noSuchMethod(
            Invocation.method(#settleAndDeactivate, [customer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
