import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:flutter/services.dart';

class ReceiptPdfGenerator {
  static Future<void> generateAndShare({
    required String customerName,
    required String phone,
    required String address,
    required int delivered,
    required int emptyCollected,
    required double paymentAmount,
    required double amountReceived,
    required String paymentMode,
    required double oldBalance,
    required double newBalance,
    required DateTime date,
    required String salesmanName,
    required String agencyName,
  }) async {
    final doc = pw.Document();
    
    pw.Font font;
    pw.Font fontBold;
    
    try {
      // Load local Helvetica font from assets
      final fontData = await rootBundle.load('assets/fonts/Helvetica/Helvetica.ttf');
      font = pw.Font.ttf(fontData);

      final fontBoldData = await rootBundle.load('assets/fonts/Helvetica/Helvetica-Bold.ttf');
      fontBold = pw.Font.ttf(fontBoldData);
    } catch (e) {
      // Fallback to built-in fonts if offline or Google Fonts fail
      font = pw.Font.helvetica();
      fontBold = pw.Font.helveticaBold();
    }

    final dateFormat = DateFormat('dd MMM yyyy, hh:mm a');

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.roll80,
        build: (pw.Context context) {
          return pw.Theme(
            data: pw.ThemeData.withFont(
              base: font,
              bold: fontBold,
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
              pw.Center(
                child: pw.Text(agencyName.toUpperCase(), textAlign: pw.TextAlign.center, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
              ),
              pw.Center(child: pw.Text("Water Delivery Service")),
              pw.Divider(),
              pw.SizedBox(height: 10),
              
              pw.Text("Date: ${dateFormat.format(date)}", style: const pw.TextStyle(fontSize: 10)),
              pw.Text("Salesman: $salesmanName", style: const pw.TextStyle(fontSize: 10)),
              pw.SizedBox(height: 5),
              
              pw.Text("Customer Details:", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
              pw.Text(customerName, style: const pw.TextStyle(fontSize: 10)),
              pw.Text(phone, style: const pw.TextStyle(fontSize: 10)),
              pw.Text(address, style: const pw.TextStyle(fontSize: 10)),
              
              pw.Divider(borderStyle: pw.BorderStyle.dashed),
              pw.SizedBox(height: 5),
              
              _buildRow("Delivered Cans", "$delivered", isBold: true),
              _buildRow("Empty Collected", "$emptyCollected"),
              
              pw.SizedBox(height: 5),
              pw.Divider(borderStyle: pw.BorderStyle.dashed),
              pw.SizedBox(height: 5),
              
              _buildRow("Total Bill", "Rs. ${paymentAmount.toInt()}", isBold: false),
              _buildRow("Amount Paid", "Rs. ${amountReceived.toInt()}", isBold: true),
              if (paymentAmount > amountReceived)
                 _buildRow("Current Due", "Rs. ${(paymentAmount - amountReceived).toInt()}"),

              _buildRow("Payment Mode", paymentMode),
              
              pw.SizedBox(height: 5),
              pw.Divider(borderStyle: pw.BorderStyle.dashed),
              pw.SizedBox(height: 5),
              
              _buildRow("Prev Balance", "Rs. ${oldBalance.toInt()}"),
              _buildRow("Total Pending", "Rs. ${newBalance.toInt()}", isBold: true),
              
              pw.SizedBox(height: 20),
              pw.Center(child: pw.Text("Thank You!", style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
              pw.SizedBox(height: 10),
              pw.Container(
                padding: const pw.EdgeInsets.all(5),
                decoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                ),
                child: pw.Text(
                  "Legal Note: This receipt is generated by the HydroFlow management platform on behalf of $agencyName. HydroFlow is a software provider and is not responsible for water quality, delivery, or service related matters.",
                  textAlign: pw.TextAlign.center,
                  style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey700),
                ),
              ),
              pw.SizedBox(height: 10),
              pw.Center(child: pw.Text("Powered by HydroFlow", style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey))),
            ],
          )); // Close Column and Theme
        },
      ),
    );

    await Printing.sharePdf(
        bytes: await doc.save(), filename: 'receipt_${DateTime.now().millisecondsSinceEpoch}.pdf');
  }

  static pw.Widget _buildRow(String label, String value, {bool isBold = false}) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(label, style: pw.TextStyle(fontSize: 10, fontWeight: isBold ? pw.FontWeight.bold : null)),
        pw.Text(value, style: pw.TextStyle(fontSize: 10, fontWeight: isBold ? pw.FontWeight.bold : null)),
      ],
    );
  }
}
