// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:watermemo/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNiCN7XGcc7O0kYUKDB3ABAAlsvkJc6k',
    appId: '1:641167599347:web:mockid',
    messagingSenderId: '641167599347',
    projectId: 'watermemo-45d4c',
    authDomain: 'watermemo-45d4c.firebaseapp.com',
    storageBucket: 'watermemo-45d4c.firebasestorage.app',
    databaseURL: 'https://watermemo-45d4c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbwqsK-h1iLz764XOeAifKH8RIazLQto',
    appId: '1:429560210914:android:27da5885808d0b5fbb45bb',
    messagingSenderId: '429560210914',
    projectId: 'hydroflow-1f649',
    storageBucket: 'hydroflow-1f649.firebasestorage.app',
    databaseURL: 'https://hydroflow-1f649-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbwqsK-h1iLz764XOeAifKH8RIazLQto',
    appId: '1:429560210914:ios:mock', // Replace with actual iOS App ID if available
    messagingSenderId: '429560210914',
    projectId: 'hydroflow-1f649',
    storageBucket: 'hydroflow-1f649.firebasestorage.app',
    databaseURL: 'https://hydroflow-1f649-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.graycodder.hydroflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbwqsK-h1iLz764XOeAifKH8RIazLQto',
    appId: '1:429560210914:ios:mock', // Replace with actual iOS App ID if available
    messagingSenderId: '429560210914',
    projectId: 'hydroflow-1f649',
    storageBucket: 'hydroflow-1f649.firebasestorage.app',
    databaseURL: 'https://hydroflow-1f649-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.graycodder.hydroflow',
  );
}
