// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:hydroflow/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNiCN7XGcc7O0kYUKDB3ABAAlsvkJc6k',
    appId: '1:641167599347:web:mockid',
    messagingSenderId: '641167599347',
    projectId: 'hydroflow-45d4c',
    authDomain: 'hydroflow-45d4c.firebaseapp.com',
    storageBucket: 'hydroflow-45d4c.firebasestorage.app',
    databaseURL: 'https://hydroflow-45d4c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaNiCN7XGcc7O0kYUKDB3ABAAlsvkJc6k',
    appId: '1:641167599347:android:4548feedf758d04b2ef986',
    messagingSenderId: '641167599347',
    projectId: 'hydroflow-45d4c',
    storageBucket: 'hydroflow-45d4c.firebasestorage.app',
    databaseURL: 'https://hydroflow-45d4c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-ios-api-key',
    appId: '1:123456789:ios:mock',
    messagingSenderId: '123456789',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosBundleId: 'com.example.hydroflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-macos-api-key',
    appId: '1:123456789:macos:mock',
    messagingSenderId: '123456789',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosBundleId: 'com.example.hydroflow',
  );
}
