// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFS-8rmI0zLPKNYtGlb02J2jumxCYgQRQ',
    appId: '1:1032293793727:web:53df1c656abae7b4feab0a',
    messagingSenderId: '1032293793727',
    projectId: 'hydroflow-stg-app',
    authDomain: 'hydroflow-stg-app.firebaseapp.com',
    databaseURL: 'https://hydroflow-stg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroflow-stg-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Vm1V4iV2G97OghPQma6Xpfa7pwb0b6c',
    appId: '1:1032293793727:android:08f805856ab0ce9efeab0a',
    messagingSenderId: '1032293793727',
    projectId: 'hydroflow-stg-app',
    databaseURL: 'https://hydroflow-stg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroflow-stg-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1pbKHsL4U9_DOoYBxj2TJlAVzwa1Y04',
    appId: '1:1032293793727:ios:dfa6eea79ef25b11feab0a',
    messagingSenderId: '1032293793727',
    projectId: 'hydroflow-stg-app',
    databaseURL: 'https://hydroflow-stg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroflow-stg-app.firebasestorage.app',
    iosBundleId: 'com.graycodder.hydroflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1pbKHsL4U9_DOoYBxj2TJlAVzwa1Y04',
    appId: '1:1032293793727:ios:dfa6eea79ef25b11feab0a',
    messagingSenderId: '1032293793727',
    projectId: 'hydroflow-stg-app',
    databaseURL: 'https://hydroflow-stg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroflow-stg-app.firebasestorage.app',
    iosBundleId: 'com.graycodder.hydroflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFS-8rmI0zLPKNYtGlb02J2jumxCYgQRQ',
    appId: '1:1032293793727:web:1374431ad6407fb8feab0a',
    messagingSenderId: '1032293793727',
    projectId: 'hydroflow-stg-app',
    authDomain: 'hydroflow-stg-app.firebaseapp.com',
    databaseURL: 'https://hydroflow-stg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroflow-stg-app.firebasestorage.app',
  );

}