import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hydroflow/features/customers/domain/entities/customer.dart';
import 'package:hydroflow/features/customers/domain/usecases/add_customer_usecase.dart';
import 'package:hydroflow/features/customers/domain/usecases/get_customers_usecase.dart';
import 'package:hydroflow/features/customers/domain/usecases/update_customer_status_usecase.dart';
import 'package:hydroflow/features/customers/domain/usecases/update_customer_usecase.dart';
import 'package:hydroflow/features/customers/domain/usecases/settle_customer_usecase.dart';
import 'package:hydroflow/features/customers/presentation/bloc/customer_event.dart';
import 'package:hydroflow/features/customers/presentation/bloc/customer_state.dart';

class CustomerBloc extends Bloc<CustomerEvent, CustomerState> {
  final GetCustomersUseCase getCustomers;
  final AddCustomerUseCase addCustomer;
  final UpdateCustomerStatusUseCase updateCustomerStatus;
  final UpdateCustomerUseCase updateCustomer;
  final SettleCustomerUseCase settleCustomer;

  CustomerBloc({
    required this.getCustomers,
    required this.addCustomer,
    required this.updateCustomerStatus,
    required this.updateCustomer,
    required this.settleCustomer,
  }) : super(const CustomerState()) {
    on<LoadCustomers>(_onLoadCustomers);

    on<AddCustomer>(_onAddCustomer);
    on<SearchCustomers>(_onSearchCustomers);
    on<UpdateCustomerStatus>(_onUpdateCustomerStatus);
    on<UpdateCustomer>(_onUpdateCustomer);
    on<SettleCustomer>(_onSettleCustomer);
  }

  Future<void> _onLoadCustomers(
    LoadCustomers event,
    Emitter<CustomerState> emit,
  ) async {
    emit(state.copyWith(status: CustomerStatus.loading));
    
    await emit.forEach<List<Customer>>(
      getCustomers(event.salesmanId),
      onData: (customers) {
        final activeCount = customers.where((c) => c.status == 'Active').length;
        final inactiveCount = customers.length - activeCount;

        return state.copyWith(
          status: CustomerStatus.success,
          customers: customers,
          filteredCustomers: customers, 
          totalCustomers: customers.length,
          activeCustomers: activeCount,
          inactiveCustomers: inactiveCount,
          successMessage: null, // Clear message on routine update
        );
      },
      onError: (error, stackTrace) => state.copyWith(
        status: CustomerStatus.failure,
        errorMessage: 'Failed to load customers: $error',
        successMessage: null,
      ),
    );
  }

  Future<void> _onAddCustomer(
    AddCustomer event,
    Emitter<CustomerState> emit,
  ) async {
    emit(state.copyWith(status: CustomerStatus.submitting, successMessage: null));
    try {
      final newCustomer = Customer(
        id: '', // Generated by Repo/DB
        salesmanId: event.salesmanId,
        name: event.name,
        phone: event.phone,
        address: event.address,
        status: 'Active',
        securityDeposit: event.securityDeposit,
        paymentMode: event.paymentMode,
      );

      await addCustomer(newCustomer);
      emit(state.copyWith(
        status: CustomerStatus.success, 
        successMessage: 'Customer added successfully',
      ));
    } catch (e) {
      emit(state.copyWith(
        status: CustomerStatus.failure,
        errorMessage: 'Failed to add customer: $e',
        successMessage: null,
      ));
    }
  }

  void _onSearchCustomers(
    SearchCustomers event,
    Emitter<CustomerState> emit,
  ) {
    if (event.query.isEmpty) {
      emit(state.copyWith(filteredCustomers: state.customers, successMessage: null));
    } else {
      final queryLower = event.query.toLowerCase();
      final filtered = state.customers.where((customer) {
        return customer.name.toLowerCase().contains(queryLower) ||
               customer.phone.contains(queryLower);
      }).toList();
      emit(state.copyWith(filteredCustomers: filtered, successMessage: null));
    }
  }

  Future<void> _onUpdateCustomerStatus(
    UpdateCustomerStatus event,
    Emitter<CustomerState> emit,
  ) async {
    emit(state.copyWith(status: CustomerStatus.submitting, successMessage: null));
    try {
      await updateCustomerStatus(event.customerId, event.status, event.salesmanId);
      emit(state.copyWith(
        status: CustomerStatus.success, 
        successMessage: 'Status updated successfully',
      ));
    } catch (e) {
       emit(state.copyWith(
        status: CustomerStatus.failure,
        errorMessage: 'Failed to update status: $e',
        successMessage: null,
      ));
    }
  }

  Future<void> _onUpdateCustomer(
    UpdateCustomer event,
    Emitter<CustomerState> emit,
  ) async {
    emit(state.copyWith(status: CustomerStatus.submitting, successMessage: null));
    try {
      await updateCustomer(event.customer);
      emit(state.copyWith(
        status: CustomerStatus.success, 
        successMessage: 'Customer updated successfully',
      ));
    } catch (e) {
      emit(state.copyWith(
        status: CustomerStatus.failure,
        errorMessage: 'Failed to update customer: $e',
        successMessage: null,
      ));
    }
  }

  Future<void> _onSettleCustomer(
    SettleCustomer event,
    Emitter<CustomerState> emit,
  ) async {
    emit(state.copyWith(status: CustomerStatus.submitting, successMessage: null));
    try {
      await settleCustomer(event.customer);
      emit(state.copyWith(
        status: CustomerStatus.success, 
        successMessage: 'Transaction settled successfully',
      ));
    } catch (e) {
       emit(state.copyWith(
        status: CustomerStatus.failure,
        errorMessage: 'Failed to settle customer: $e',
        successMessage: null,
      ));
    }
  }
}
