import 'package:flutter/material.dart';
import 'package:watermemo/features/auth/domain/entities/salesman.dart';
import 'package:flutter/services.dart';
import 'package:watermemo/features/auth/domain/repositories/agency_repository.dart';
import 'package:watermemo/core/service_locator.dart' as di;
import 'package:watermemo/core/widgets/hydro_flow_loader.dart';

class AddSalesmanDialog extends StatefulWidget {
  final String agencyId;
  final String agencyName;
  final int maxAgencyCustomers;
  final List<Salesman> existingSalesmen;

  const AddSalesmanDialog({
    super.key,
    required this.agencyId,
    required this.agencyName,
    this.maxAgencyCustomers = 0,
    this.existingSalesmen = const [],
  });

  @override
  State<AddSalesmanDialog> createState() => _AddSalesmanDialogState();
}

class _AddSalesmanDialogState extends State<AddSalesmanDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
 // final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  // final _quotaController = TextEditingController();
  bool _isChecking = false;
  bool _isPasswordVisible = false;
  String? _phoneError;

  @override
  void initState() {
    super.initState();
    _phoneController.addListener(_onPhoneChanged);
  }


  void _onPhoneChanged() {
    if (_phoneError != null) {
      setState(() {
        _phoneError = null;
      });
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    // _usernameController.dispose();
    _passwordController.dispose();
   // _quotaController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_formKey.currentState!.validate()) {
      FocusScope.of(context).unfocus();
      FocusManager.instance.primaryFocus?.unfocus();

      // Give keyboard a moment to dismiss
      await Future.delayed(const Duration(milliseconds: 100));
      if (!mounted) return;

      setState(() => _isChecking = true);
      WaterMemoLoader.show(context, message: 'Checking phone number...');

      try {
        final repo = di.sl<AgencyRepository>();
        final phone = _phoneController.text.trim();
        final isUnique = await repo.isPhoneNumberUnique(phone);

        if (!mounted) return;
        WaterMemoLoader.hide(context);

        if (!isUnique) {
          setState(() {
            _isChecking = false;
            _phoneError = 'Phone number already in use';
          });
          return;
        }

        final newSalesman = Salesman(
          id: '', // Will be generated by repo
          name: _nameController.text.trim(),
          username: phone,
          password: _passwordController.text.trim(),
          role: 'salesman',
          agencyId: widget.agencyId,
          agencyName: widget.agencyName,
          phoneNumber: phone,
          address: '', // Optional or add field
          zone: 'all',
          maxCustomers: 0,
          createdAt: DateTime.now(), 
        );

        FocusScope.of(context).unfocus();
        FocusManager.instance.primaryFocus?.unfocus();
        Navigator.pop(context, newSalesman);
      } catch (e) {
        if (mounted) {
          WaterMemoLoader.hide(context);
          setState(() => _isChecking = false);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error validating phone number: $e')),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Salesman'),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
               const SizedBox(height: 12),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Full Name'),
                inputFormatters: [
                  FilteringTextInputFormatter.allow(RegExp(r'[a-zA-Z0-9 ]')),
                ],
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter name';
                  }
                  if (value.trim().length > 20) {
                    return 'Name must be at most 20 characters';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _phoneController,
                decoration: InputDecoration(
                  labelText: 'Phone Number',
                  errorText: _phoneError,
                ),
                keyboardType: TextInputType.phone,
                inputFormatters: [
                  FilteringTextInputFormatter.digitsOnly,
                  LengthLimitingTextInputFormatter(10),
                ],
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter phone number';
                  }
                  if (value.trim().length != 10) {
                    return 'Phone number must be exactly 10 digits';
                  }
                  return null;
                },
              ),
              //  const SizedBox(height: 12),
              // TextFormField(
              //   controller: _usernameController,
              //   decoration: const InputDecoration(labelText: 'Username (for Login)'),
              //   inputFormatters: [
              //     FilteringTextInputFormatter.allow(RegExp(r'[a-zA-Z0-9_]')),
              //   ],
              //   validator: (value) {
              //     if (value == null || value.trim().isEmpty) {
              //       return 'Please enter username';
              //     }
              //     if (value.trim().length > 15) {
              //       return 'Username must be at most 15 characters';
              //     }
              //     if (value.contains(' ')) {
              //       return 'Spaces are not allowed';
              //     }
              //     return null;
              //   },
              // ),
               const SizedBox(height: 12),
              TextFormField(
                controller: _passwordController,
                decoration: InputDecoration(
                  labelText: 'Password',
                  prefixIcon: const Icon(Icons.lock_outline),
                  suffixIcon: IconButton(
                    icon: Icon(
                      _isPasswordVisible ? Icons.visibility : Icons.visibility_off,
                    ),
                    onPressed: () {
                      setState(() {
                        _isPasswordVisible = !_isPasswordVisible;
                      });
                    },
                  ),
                ),
                obscureText: !_isPasswordVisible,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter password';
                  }
                  if (value.length < 6) {
                    return 'Min 6 characters';
                  }
                  return null;
                },
              ),
               const SizedBox(height: 12),
              // const SizedBox(height: 12),
              // Builder(
              //   builder: (context) {
              //     final alreadyAllocated = widget.existingSalesmen.fold<int>(0, (sum, s) => sum + s.maxCustomers);
              //     final remaining = (widget.maxAgencyCustomers - alreadyAllocated).clamp(0, widget.maxAgencyCustomers);
                  
              //     return TextFormField(
              //       controller: _quotaController,
              //       decoration: InputDecoration(
              //         labelText: 'Customer Quota',
              //         helperText: 'Agency Limit: ${widget.maxAgencyCustomers}. Already Allocated: $alreadyAllocated. Available to Assign: $remaining',
              //         helperMaxLines: 3,
              //       ),
              //       keyboardType: TextInputType.number,
              //       inputFormatters: [
              //         FilteringTextInputFormatter.digitsOnly,
              //       ],
              //       onChanged: (value) {
              //         if (value.length > 1 && value.startsWith('0')) {
              //           String newText = value.replaceFirst(RegExp(r'^0+'), '');
              //           if (newText.isEmpty) newText = '0';
              //           _quotaController.value = TextEditingValue(
              //             text: newText,
              //             selection: TextSelection.collapsed(offset: newText.length),
              //           );
              //         }
              //       },
              //       validator: (value) {
              //         if (value == null || value.isEmpty) return 'Please enter quota';
              //         final qty = int.tryParse(value);
              //         if (qty == null || qty < 0) return 'Enter a valid number';
                      
              //         if (qty > remaining) {
              //           return 'Exceeds Agency Limit ($remaining remaining)';
              //         }
              //         return null;
              //       },
              //     );
              //   },
              // ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _isChecking ? null : _submit,
          child: _isChecking 
            ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
            : const Text('Add Salesman'),
        ),
      ],
    );
  }

}
