import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hydroflow/features/auth/domain/entities/salesman.dart';
import 'package:hydroflow/features/auth/presentation/bloc/agency_bloc.dart';
import 'package:hydroflow/features/auth/presentation/bloc/agency_event.dart';

class AddSalesmanDialog extends StatefulWidget {
  final String agencyId;
  final String agencyName;
  final int maxAgencyCustomers;
  final List<Salesman> existingSalesmen;

  const AddSalesmanDialog({
    super.key,
    required this.agencyId,
    required this.agencyName,
    this.maxAgencyCustomers = 0,
    this.existingSalesmen = const [],
  });

  @override
  State<AddSalesmanDialog> createState() => _AddSalesmanDialogState();
}

class _AddSalesmanDialogState extends State<AddSalesmanDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  final _zoneController = TextEditingController();
  final _quotaController = TextEditingController(text: '250');

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _usernameController.dispose();
    _passwordController.dispose();
    _zoneController.dispose();
    _quotaController.dispose();
    super.dispose();
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      final newSalesman = Salesman(
        id: '', // Will be generated by repo
        name: _nameController.text.trim(),
        username: _usernameController.text.trim(),
        password: _passwordController.text.trim(),
        role: 'salesman',
        agencyId: widget.agencyId,
        agencyName: widget.agencyName,
        phoneNumber: _phoneController.text.trim(),
        address: '', // Optional or add field
        zone: _zoneController.text.trim(),
        maxCustomers: int.tryParse(_quotaController.text) ?? 0,
        createdAt: DateTime.now(), 
      );

      // We use the Bloc from the parent context (AgencyEmployeesPage)
      // Since Dialog is pushed, we need to ensure context has the provider.
      // AgencyEmployeesPage uses BlocProvider. Dialog is usually above that in overlay.
      // So we typically pass the bloc or wrap dialog in provider, 
      // OR we just assume the caller handles the event dispatch.
      // Better: Return the Salesman object and let the caller dispatch.
      
      Navigator.pop(context, newSalesman);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Salesman'),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Full Name'),
                validator: (value) =>
                    value == null || value.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _phoneController,
                decoration: const InputDecoration(labelText: 'Phone Number'),
                keyboardType: TextInputType.phone,
                validator: (value) =>
                    value == null || value.isEmpty ? 'Required' : null,
              ),
               const SizedBox(height: 12),
              TextFormField(
                controller: _usernameController,
                decoration: const InputDecoration(labelText: 'Username (for Login)'),
                validator: (value) =>
                    value == null || value.isEmpty ? 'Required' : null,
              ),
               const SizedBox(height: 12),
              TextFormField(
                controller: _passwordController,
                decoration: const InputDecoration(labelText: 'Password'),
                obscureText: true,
                validator: (value) =>
                    value == null || value.length < 6 ? 'Min 6 chars' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _zoneController,
                decoration: const InputDecoration(labelText: 'Zone (Optional)'),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _quotaController,
                decoration: const InputDecoration(
                  labelText: 'Customer Quota',
                  helperText: 'Max customers this salesman can manage',
                ),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) return 'Required';
                  final qty = int.tryParse(value);
                  if (qty == null) return 'Enter a valid number';
                  
                  final alreadyAllocated = widget.existingSalesmen.fold<int>(0, (sum, s) => sum + s.maxCustomers);
                  final remaining = widget.maxAgencyCustomers - alreadyAllocated;
                  
                  if (qty > remaining) {
                    return 'Exceeds Agency Limit ($remaining remaining)';
                  }
                  return null;
                },
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _submit,
          child: const Text('Add Salesman'),
        ),
      ],
    );
  }
}
